[build]
  command = "npm run build"
  publish = "dist"
  

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["pdf-parse"]

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 8888
[[redirects]]
  from = "/api/upload"
  to = "/.netlify/functions/api"
  status = 200

[[redirects]]
  from = "/api/query"
  to = "/.netlify/functions/api"
  status = 200
