[build]
  functions = "netlify/functions"
  publish = "dist"  # Or the directory where your Vite app is built

[functions]
  node_bundler = "esbuild"

[dev]
  framework = "vite"
  command = "npm run dev"
  port = 3000


